# Not an actual docker-compose, just a sample.

services:
  service-name:
    container_name: vc-participant
    build:
      context: .
      dockerfile: Dockerfile
    command: fastapi run --port 8000
    ports:
      - 8530:8000
    env_file:
      - config/environments/.env.production
    depends_on:
      - vc-participant-db
    restart: always
    networks:
      - vc-participant-network

  vc-participant-db:
    container_name: vc-participant-db
    image: postgres:16.3
    ports:
      - 5070:5432
    env_file:
      - config/environments/.env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docs/database/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: always
    networks:
      - vc-participant-network

volumes:
  postgres_data:

networks:
  custom-network:
    driver: bridge
